![Logo UNC Chapel Hill]()

# Notebook 05
**Course:** *Econ 590, Computational Methods for Economists*, [University of North Carolina at Chapel Hill](https://econ.unc.edu/), Spring 2025  
**Instructor:** [Marlon Azinovic-Yang](https://sites.google.com/view/marlonazinovic/home)  
**Contact:** marlonay@unc.edu  
**References:** This notebook has benefited greatly from the teaching material and notebooks generously made available by [Simon Scheidegger](https://sites.google.com/site/simonscheidegger/home), [Felix Kubler](https://sites.google.com/site/fkubler/), [Harold Linh Cole](https://economics.sas.upenn.edu/people/harold-l-cole), [Jeremy Greenwood](https://www.jeremygreenwood.net/), [Jeppe Druedahl](https://sites.google.com/view/jeppe-druedahl/), [Rick Evans](https://sites.google.com/site/rickecon/), and by [Tom Sargent](http://www.tomsargent.com/) and [John Stachurski](https://johnstachurski.net/) on [QuantEcon](https://quantecon.org/).

## Content
The goal of this notebook is to give an introduction to the concept of containers in python. Examples of containers are lists, tuples, and dictionaries. Containers in python are objects that can hold multiple items. This allows us to store and manipulate collections of data. We will consider three types of containers: 1) Lists, 2) Dictionaries, and 3) Tuples.
### Lists
A **list** is an *ordered* and *mutable* collection that allows us to store elements of different data types and allows for *duplicate* elements.  

*Ordered* means that the order of the elements is preserved. You can think of this as books on a bookshelf: you can refer to the second book and the third book and so on. This is different to books in a big bag, where you know that the books are in there, but there is no obvious way to order them. 

*Mutable* means that elements can be added, removed, or changed. E.g. we can take book 4 from the bookshelf, take it out and replace it by another book. Or we can take book 4 from the shelf, and throw it away completely. In this case the book that was previously book 5 will now become book 4. Analogously we can insert a new book to the very left, becoming the new book 1. If we want, we can even take out book 4 and put something else in it's place. Like a little Mercedes toy car for example. Now the item number 4 is the toy mercedes, but all other items are books. A mutable object refers to a place in memory. Like refering to a specific bookshelf in our house. When a mutable object is modified, the changes occur in the same memory location without creating a new object.
This is why modifications to a mutable object via one reference will be visible to all other references pointing to the same object. If we have two mutable objects refering to the same bookshelf, if we change a book in that shelf, it will change for all objects pointing to that shelf.

*Duplicate* elements means that I can have the same element in multiple places of the list. To explain this, I could not think of a good bookshelf analogy, since lists would allow you to have the same physical book in multiple places on the shelf, not just different copies of the same book but literally the same book. As a counterexample you can maybe think of a regular language dictionary, where each word only appears once. More on dictionaries in python will come later. 
We can define an empyt list using `mylist = []`, or define a non-empty list with `fruits = ["apple", "banana"]`. Let's make some examples:

In [1]:
fruits = ['orange', 'apple', 'pear', 'banana', 'kiwi', 'apple', 'watermelon'] # define a list of strings
print("1 fruits = ", fruits)

# we can access elements in a list using their index
print("element[0] = ", fruits[0]) # prints the first element in the list
print("element[1] = ", fruits[1]) # prints the second element in the list
print("element[-1] = ", fruits[-1]) # prints the last element in the list

1 fruits =  ['orange', 'apple', 'pear', 'banana', 'kiwi', 'apple', 'watermelon']
element[0] =  orange
element[1] =  apple
element[-1] =  watermelon

In [2]:
# we can replace elements in a list using their index
fruits[1] = 'mango'

**Exercise**: Will `print(fruits)` show?

In [3]:
# we can have duplicate elements in a list
fruits[0] = 'mango'

**Exercise**: Will `print(fruits)` show?

In [4]:
# we can add elements in a list using the append() method
fruits.append('grape')

**Exercise**: Will `print(fruits)` show?

In [5]:
# or we can add elements at a sepcific place in the list using the insert() method
fruits.insert(1, 'strawberry')

**Exercise**: Will `print(fruits)` show?

In [15]:
# we can remove elements from a list using the remove() method
fruits.remove('banana')

**Exercise**: Will `print(fruits)` show?

In [6]:
# we can have elements of different types in the list
fruits[1] = 590

In [7]:
# a list has a length which can be obtained using the len() function
print("len(fruits) = ", len(fruits))

len(fruits) =  9

In [8]:
# now we remove the pear
fruits.remove('pear')

In [9]:
# and check the length again
print("len(fruits) = ", len(fruits))

len(fruits) =  8

In [10]:
# we can use the in operator to check if an element is in a list
print("orange in fruits = ", 'orange' in fruits)
print("mango in fruits = ", 'mango' in fruits)

orange in fruits =  False
mango in fruits =  True

Lists are also very useful because we can iterate through them.

In [11]:
for fruit in fruits:
    print(fruit)

mango
590
mango
banana
kiwi
apple
watermelon
grape

In [12]:
for i in range(len(fruits)):
    print(fruits[i])

mango
590
mango
banana
kiwi
apple
watermelon
grape

#### Exercise
1. Create a list of fruits you like
2. Create a list of fruits you dislike
3. Write a function `doIlike(fruit)` that takes a fruit as an input and then prints out whether you like or dislike the fruit or whether you are neutral towards the fruit.

In [13]:
print(doIlike("Apple"))
print(doIlike("Banana"))
print(doIlike("Coconut"))

NameError: name 'doIlike' is not defined

#### IMPORTANT DIFFERENCE TO MATLAB: copies of lists and lists of mutable objects
So far we just looked at lists of strings and numbers. Strings and numbers are *immutable* objects. However, we can also have lists of mutable objects such as lists of lists. In this case it is important to know that for mutable objects the list stores references to the place of the objects in memory. So if we change those values, the list will change. Let's consider an example.

In [14]:
a = "Econ"
b = 590
c = ["UNC <3"]

testlist = [a, b, c]
print("testlist = ", testlist)

# now, what happens if we change the value of a?
print("type(a) = ", type(a))
a = "Math"

testlist =  ['Econ', 590, ['UNC <3']]
type(a) =  <class 'str'>

**Exercise**: What does `print(testlist)` show?

In [15]:
# now, what happens if we change the value of c?
print("type(c) = ", type(c))
c[0] = "Duke =("

type(c) =  <class 'list'>

**Exercise**: What does `print(testlist)` show?

This is because lists are mutable objects and point to places in memory.  
Similarly, if we just use `list1 = list2`, then they are pointing to the same bookshelf. So if I use one of the lists to change a book in the bookshelf, the book will also change in the other list. This can lead to dangerours mistakes. Let's consider an example.

In [16]:
testlist = ["USA", "Canada", "Mexico"]

testlist2 = testlist # this does not create a copy of testlist, it creates a reference to it

print("testlist = ", testlist)
print("testlist2 = ", testlist2)

testlist =  ['USA', 'Canada', 'Mexico']
testlist2 =  ['USA', 'Canada', 'Mexico']

In [17]:
testlist2[0] = "Germany"
print("2 testlist = ", testlist)
print("2 testlist2 = ", testlist2)
print("BOTH LISTS CHANGED")
print("WHY? BECAUSE testlist2 IS A REFERENCE TO testlist, NOT A COPY OF IT")
print("id(testlist) = ", id(testlist))
print("id(testlist2) = ", id(testlist2))

2 testlist =  ['Germany', 'Canada', 'Mexico']
2 testlist2 =  ['Germany', 'Canada', 'Mexico']
BOTH LISTS CHANGED
WHY? BECAUSE testlist2 IS A REFERENCE TO testlist, NOT A COPY OF IT
id(testlist) =  124366118660992
id(testlist2) =  124366118660992

Sometimes, we do not want that, we may want to be able to change elements in `testlist2` without changing elements in `testlist`. So we want those two lists to point to *two different places in memory*, which are initially filled with the same elements. We can do this by using `copy.deepcopy`. This will create a copy of the list in a different place in memory. This is like buying the same bookshelf and the same books and then putting it into a different room. Now I can change the books on one bookshelf without changing the books on the other. Let's try it.

In [18]:
testlist = ["USA", "Canada", "Mexico"]


import copy # we need to import the copy module to use the deepcopy() function
testlist2 = copy.deepcopy(testlist) # this DOES create a copy of testlist

print("1 testlist = ", testlist)
print("1 testlist2 = ", testlist2)

testlist2[0] = "Germany"
print("2 testlist = ", testlist)
print("2 testlist2 = ", testlist2)
print("Now testlist remains unchanged")

1 testlist =  ['USA', 'Canada', 'Mexico']
1 testlist2 =  ['USA', 'Canada', 'Mexico']
2 testlist =  ['USA', 'Canada', 'Mexico']
2 testlist2 =  ['Germany', 'Canada', 'Mexico']
Now testlist remains unchanged

### Tuples
A **tuple** is an *ordered*, *immutable* collection of elements in Python. Typles are similar to lists but their contents can not be changed after they are created. As for lists, we can put different types together into a tuple. We can create a tuple by using the round brackets `mytuple =  (a, b)` or by simply using a `,` only: `mytuple =  a, b`.

In [19]:
mytuple = (1, 2, "Econ590")

print("mytuple = ", mytuple)
print("mytuple[0] = ", mytuple[0])
print("mytuple[1] = ", mytuple[1])
print("mytuple[2] = ", mytuple[2])

mytuple =  (1, 2, 'Econ590')
mytuple[0] =  1
mytuple[1] =  2
mytuple[2] =  Econ590

Tuples are immutable, so we can't change a specific entry of the tuple after creation.

In [20]:

mytuple[0] = 3 # this will raise an error, because tuples are immutable

TypeError: 'tuple' object does not support item assignment

In [21]:
# we can read out values from a tuple
a, b, c = mytuple
print("a = ", a)
print("b = ", b)
print("c = ", c)

a =  1
b =  2
c =  Econ590

We have already encountered tuples: if we define a function with multpile return values, the function actually returns a tuple.

In [23]:
def compute_powers(number):
    return number**2, number**3, number**4

res = compute_powers(3)

In [25]:

print("res = ", res)
print("type(res) = ", type(res))
print("res[0] = ", res[0])
print("res[1] = ", res[1])
print("res[2] = ", res[2])

# alternatively we can also do
a, b, c = compute_powers(3)
print("a = ", a)
print("b = ", b)
print("c = ", c)

res =  (9, 27, 81)
type(res) =  <class 'tuple'>
res[0] =  9
res[1] =  27
res[2] =  81
a =  9
b =  27
c =  81

### Dictionaries
A **dictionary** is a *mutable* collection of *key-value* pairs. Keys have to be immutable objects like numbers or strings and can't have duplicates. We can create and empy dictionary by using `{}` or fill it with values using `{key : value}` syntax. Keys and values do not need to be the same type and values are allowed to be mutable objects (like lists). Each key in a dictionary is unique and assigned to a value.

In [26]:
coursedict = {}

coursedict["Name"] = "Econ 590"
coursedict["Instructor"] = "Marlon"
coursedict["Location"] = "Gardner 211"
coursedict["Time"] = "TTh 3:30pm-4:45pm"
coursedict["NumStudents"] = 3
coursedict["Students"] = ["Alice", "Bob", "Charlie"]

print(coursedict)

# equivalently, we could have defined the dictionary as follows
coursedict = {"Name": "Econ 590", "Instructor": "Marlon", "Location": "Gardner 211", "Time": "TTh 3:30pm-4:45pm", "NumStudents": 3, "Students": ["Alice", "Bob", "Charlie"]}
print(coursedict)

{'Name': 'Econ 590', 'Instructor': 'Marlon', 'Location': 'Gardner 211', 'Time': 'TTh 3:30pm-4:45pm', 'NumStudents': 3, 'Students': ['Alice', 'Bob', 'Charlie']}
{'Name': 'Econ 590', 'Instructor': 'Marlon', 'Location': 'Gardner 211', 'Time': 'TTh 3:30pm-4:45pm', 'NumStudents': 3, 'Students': ['Alice', 'Bob', 'Charlie']}

In [27]:
# a dictionary is useful because we can quickly access the value of a key
print(coursedict['Name'], "happens at", coursedict['Time'], "in", coursedict['Location'])

# we can change the value of a key
coursedict['Location'] = "Gardner 213"
print("Location is now" , coursedict['Location'])

# we can add a new key
coursedict['NumCredits'] = 3
print(coursedict)

Econ 590 happens at TTh 3:30pm-4:45pm in Gardner 211
Location is now Gardner 213
{'Name': 'Econ 590', 'Instructor': 'Marlon', 'Location': 'Gardner 213', 'Time': 'TTh 3:30pm-4:45pm', 'NumStudents': 3, 'Students': ['Alice', 'Bob', 'Charlie'], 'NumCredits': 3}

In [28]:
# items in a dictionary are key value pairs
for key, value in coursedict.items():
    print(key, ":", value)

# we can check if a key is in a dictionary
print("Name in coursedict = ", 'Name' in coursedict)
print("NumCredits in coursedict = ", 'NumCredits' in coursedict)
print("Grades in coursedict = ", 'Grades' in coursedict)

Name : Econ 590
Instructor : Marlon
Location : Gardner 213
Time : TTh 3:30pm-4:45pm
NumStudents : 3
Students : ['Alice', 'Bob', 'Charlie']
NumCredits : 3
Name in coursedict =  True
NumCredits in coursedict =  True
Grades in coursedict =  False

In [29]:

# we can also iterate over the keys in a dictionary
for key in coursedict.keys():
    print('key = ', key)
    print('coursedict[key] = ', coursedict[key])

key =  Name
coursedict[key] =  Econ 590
key =  Instructor
coursedict[key] =  Marlon
key =  Location
coursedict[key] =  Gardner 213
key =  Time
coursedict[key] =  TTh 3:30pm-4:45pm
key =  NumStudents
coursedict[key] =  3
key =  Students
coursedict[key] =  ['Alice', 'Bob', 'Charlie']
key =  NumCredits
coursedict[key] =  3

Values are allowed to be complicated objects, like nested lists or dictionaries. This can be useful. Assume we want to store the grades for each (fictional) student abd that their are grades for `"HW1"`, `"HW2"`, `"Midterm"`. For each student, I can store the grades in a dictionary. Then I can make another dictionary that maps each student name to their grade dictionary. And now I can store that grades dictionary into the course dictionary under (say) `"Grades"`. Let's see how this works.

In [30]:
grades_Alice = {"HW1": 90, "HW2": 85, "Midterm": 80}
grades_Bob = {"HW1": 80, "HW2": 75, "Midterm": 70}
grades_Charlie = {"HW1": 70, "HW2": 65, "Midterm": 60}

grades = {"Alice": grades_Alice, "Bob": grades_Bob, "Charlie": grades_Charlie}

coursedict["Grades"] = grades

#### Hard exercise
Write code that extends the dictionaries at `coursedict['Grades']['Studentname']` with a key `'Average'` and a value equal to the average of the grades for `'HW1'`, `'HW2'`, and `'Midterm'`.

In [31]:
# hint
# loop through the students
for student in coursedict["Students"]: # iterate over the students in the course
    print("Grades for", student)

    # get the grades for the student
    grades = coursedict["Grades"][student]
    print("grades = ", grades)
    
    # read out the grades from the dictionary
    gradehw1 = grades["HW1"]
    gradehw2 = grades["HW2"]
    grademidterm = grades["Midterm"]

    print("HW1:", gradehw1)
    print("HW2:", gradehw2)
    print("Midterm:", grademidterm)    

    # compute the averge grade
    # TODO

    # store the average grade in the dictionary
    # TODO

    print(" ")

Grades for Alice
grades =  {'HW1': 90, 'HW2': 85, 'Midterm': 80}
HW1: 90
HW2: 85
Midterm: 80

Grades for Bob
grades =  {'HW1': 80, 'HW2': 75, 'Midterm': 70}
HW1: 80
HW2: 75
Midterm: 70

Grades for Charlie
grades =  {'HW1': 70, 'HW2': 65, 'Midterm': 60}
HW1: 70
HW2: 65
Midterm: 60

Commonly used methods for dictionaries include the following:

| **Method**        | **Description**                                   | **Example**                               |
|--------------------|---------------------------------------------------|-------------------------------------------|
| `get(key, default)`| Returns the value for the key, or `default`.      | `my_dict.get('key', 'default_value')`     |
| `keys()`           | Returns all keys as a view object.               | `my_dict.keys()`                          |
| `values()`         | Returns all values as a view object.             | `my_dict.values()`                        |
| `items()`          | Returns all key-value pairs as a view object.    | `my_dict.items()`                         |
| `update()`         | Updates the dictionary with key-value pairs.     | `my_dict.update({'new_key': 'value'})`    |
| `pop(key)`         | Removes and returns the value for the key.       | `my_dict.pop('key')`                      |
| `clear()`          | Removes all key-value pairs.                     | `my_dict.clear()`                         |

### Comparison
| **Feature**       | **List**                        | **Dictionary**                 | **Tuple**                   |
|--------------------|---------------------------------|--------------------------------|-----------------------------|
| **Ordered**        | Yes                             | Not before Python 3.7          | Yes                        |
| **Mutable**        | Yes                             | Yes                            | No                          |
| **Duplicates**     | Allowed                         | Keys: No, Values: Yes          | Allowed                     |
| **Use Case**       | General-purpose collection      | Lookup by keys                 | Immutable data or constants |